import { Persona, AuditLog, DashboardMetrics } from "./types";

export const mockPersonas: Persona[] = [
  {
    id: "p001",
    nric: "S9812345A",
    name: "Tan Wei Ming",
    type: "partner_integration",
    status: "active",
    owner: "GovTech RP Team",
    createdBy: "alice.lim@govtech.gov.sg",
    createdAt: "2025-01-15T08:30:00Z",
    expiresAt: "2025-04-15T00:00:00Z",
    lastModified: "2025-03-02T14:20:00Z",
    lifecycleStage: "usage",
    environment: "staging",
    systems: { singpass: true, myinfo: true, corppass: false, mib: false },
    tags: ["myinfo-v4", "login-flow", "govtech"],
    modificationRights: "limited",
    attributes: {
      sex: "M",
      race: "Chinese",
      nationality: "Singapore Citizen",
      dob: "1998-06-12",
      email: "tanwm.test@example.com",
      mobile: "+6591234567",
      educationLevel: "Degree",
      residentialStatus: "Citizen",
      housingType: "HDB 4-Room",
    },
  },
  {
    id: "p002",
    nric: "T0234567B",
    name: "Priya Nair",
    type: "partner_integration",
    status: "active",
    owner: "CPF Board RP Team",
    createdBy: "bob.chen@cpf.gov.sg",
    createdAt: "2025-02-01T10:00:00Z",
    expiresAt: "2025-05-01T00:00:00Z",
    lastModified: "2025-03-10T09:15:00Z",
    lifecycleStage: "usage",
    environment: "staging",
    systems: { singpass: true, myinfo: true, corppass: true, mib: false },
    tags: ["myinfo-v4", "corppass-admin", "cpf"],
    modificationRights: "limited",
    attributes: {
      sex: "F",
      race: "Indian",
      nationality: "Singapore Citizen",
      dob: "2002-03-25",
      email: "priya.test@example.com",
      mobile: "+6598765432",
      educationLevel: "Diploma",
      residentialStatus: "Citizen",
      housingType: "Private",
    },
  },
  {
    id: "p003",
    nric: "S8567890C",
    name: "Ahmad Bin Razali",
    type: "business_entity",
    status: "active",
    owner: "Singpass / Corppass / PX",
    entityUen: "202312345A",
    entityName: "Tech Solutions Pte Ltd",
    createdBy: "px.ops@singpass.gov.sg",
    createdAt: "2025-01-20T14:00:00Z",
    expiresAt: "2025-07-20T00:00:00Z",
    lastModified: "2025-02-28T11:30:00Z",
    lifecycleStage: "usage",
    environment: "staging",
    systems: { singpass: true, myinfo: true, corppass: true, mib: true },
    tags: ["acra-entity", "corppass-admin", "myinfo-biz"],
    modificationRights: "none",
    attributes: {
      sex: "M",
      race: "Malay",
      nationality: "Singapore Citizen",
      dob: "1985-11-08",
      email: "ahmad.test@example.com",
      mobile: "+6587654321",
      entityType: "Private Limited",
      corppassRole: "Admin",
      noOfEmployees: 50,
    },
  },
  {
    id: "p004",
    nric: "G1234567K",
    name: "Lee Hui Ling",
    type: "synthetic_reliability",
    status: "active",
    owner: "Singpass Automation",
    createdBy: "automation@singpass.gov.sg",
    createdAt: "2025-01-01T00:00:00Z",
    expiresAt: "2025-12-31T00:00:00Z",
    lastModified: "2025-03-14T03:00:00Z",
    lifecycleStage: "usage",
    environment: "staging",
    systems: { singpass: true, myinfo: true, corppass: false, mib: false },
    tags: ["synthetic", "load-test", "auto-refresh"],
    modificationRights: "automated",
    attributes: {
      sex: "F",
      race: "Chinese",
      nationality: "Singapore Citizen",
      dob: "1990-04-17",
      email: "synthetic.test01@example.com",
      mobile: "+6511111111",
      residentialStatus: "Citizen",
    },
  },
  {
    id: "p005",
    nric: "S7123456D",
    name: "Ravi Krishnamurthy",
    type: "security_testing",
    status: "active",
    owner: "Singpass / CSG",
    createdBy: "csg.security@govtech.gov.sg",
    createdAt: "2025-03-01T09:00:00Z",
    expiresAt: "2025-04-01T00:00:00Z",
    lastModified: "2025-03-12T16:45:00Z",
    lifecycleStage: "usage",
    environment: "staging",
    systems: { singpass: true, myinfo: true, corppass: false, mib: false },
    tags: ["vdp", "gbbp", "security"],
    modificationRights: "full",
    attributes: {
      sex: "M",
      race: "Indian",
      nationality: "Singapore Citizen",
      dob: "1975-09-30",
      email: "ravi.sec@example.com",
      mobile: "+6599999999",
    },
  },
  {
    id: "p006",
    nric: "T1898765E",
    name: "Wong Siew Ling",
    type: "partner_configured",
    status: "expiring",
    owner: "MOM RP Team",
    createdBy: "dev.team@mom.gov.sg",
    createdAt: "2024-12-20T08:00:00Z",
    expiresAt: "2025-03-20T00:00:00Z",
    lastModified: "2025-03-01T10:00:00Z",
    lifecycleStage: "usage",
    environment: "staging",
    systems: { singpass: true, myinfo: true, corppass: false, mib: false },
    tags: ["edge-case", "myinfo-v3", "mom"],
    modificationRights: "limited",
    attributes: {
      sex: "F",
      race: "Chinese",
      nationality: "Singapore PR",
      dob: "1989-12-05",
      email: "wong.test@example.com",
      mobile: "+6577777777",
      passType: "S Pass",
      residentialStatus: "PR",
    },
  },
  {
    id: "p007",
    nric: "S6234567F",
    name: "Iskandar Bin Hassan",
    type: "synthetic_monitoring",
    status: "active",
    owner: "ICA / Singpass",
    createdBy: "automation@singpass.gov.sg",
    createdAt: "2025-01-10T00:00:00Z",
    expiresAt: "2025-12-31T00:00:00Z",
    lastModified: "2025-03-14T06:00:00Z",
    lifecycleStage: "usage",
    environment: "staging",
    systems: { singpass: true, myinfo: false, corppass: false, mib: false },
    tags: ["synthetic", "agency-monitoring", "ica"],
    modificationRights: "none",
    attributes: {
      sex: "M",
      race: "Malay",
      nationality: "Singapore Citizen",
      dob: "1982-07-20",
      email: "iskandar.mon@example.com",
      mobile: "+6522222222",
    },
  },
  {
    id: "p008",
    nric: "T9345678G",
    name: "Chen Xiao Wei",
    type: "partner_integration",
    status: "provisioning",
    owner: "MOE RP Team",
    createdBy: "admin@moe.gov.sg",
    createdAt: "2025-03-14T15:00:00Z",
    expiresAt: "2025-06-14T00:00:00Z",
    lastModified: "2025-03-14T15:00:00Z",
    lifecycleStage: "creation",
    environment: "staging",
    systems: { singpass: true, myinfo: false, corppass: false, mib: false },
    tags: ["myinfo-v4", "moe"],
    modificationRights: "limited",
    attributes: {
      sex: "M",
      race: "Chinese",
      nationality: "Singapore Citizen",
      dob: "2000-01-15",
    },
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: "a001",
    personaId: "p008",
    personaNric: "T9345678G",
    action: "create",
    actor: "admin@moe.gov.sg",
    actorRole: "RP Admin",
    timestamp: "2025-03-14T15:00:12Z",
    details: "New partner integration persona created. Singpass account provisioned. Myinfo injection pending.",
    systems: ["singpass"],
    ipAddress: "10.20.30.41",
  },
  {
    id: "a002",
    personaId: "p005",
    personaNric: "S7123456D",
    action: "modify",
    actor: "csg.security@govtech.gov.sg",
    actorRole: "CSG Security",
    timestamp: "2025-03-12T16:45:30Z",
    details: "Myinfo attributes updated for VDP scenario: residentialStatus changed to PR for edge-case testing.",
    systems: ["myinfo"],
    ipAddress: "10.20.30.15",
  },
  {
    id: "a003",
    personaId: "p006",
    personaNric: "T1898765E",
    action: "access",
    actor: "dev.team@mom.gov.sg",
    actorRole: "RP Developer",
    timestamp: "2025-03-14T09:22:00Z",
    details: "Persona accessed for integration test run. Myinfo v3 data pulled via /person endpoint.",
    systems: ["singpass", "myinfo"],
    ipAddress: "203.45.67.89",
  },
  {
    id: "a004",
    personaId: "p003",
    personaNric: "S8567890C",
    action: "modify",
    actor: "px.ops@singpass.gov.sg",
    actorRole: "PX Ops",
    timestamp: "2025-02-28T11:30:00Z",
    details: "Corppass entity linked to individual account. Role updated to Admin for Tech Solutions Pte Ltd (UEN: 202312345A).",
    systems: ["corppass"],
    ipAddress: "10.20.30.5",
  },
  {
    id: "a005",
    personaId: "p004",
    personaNric: "G1234567K",
    action: "modify",
    actor: "automation@singpass.gov.sg",
    actorRole: "Automation System",
    timestamp: "2025-03-14T03:00:00Z",
    details: "Automated data refresh cycle completed. Persona attributes refreshed for synthetic reliability testing.",
    systems: ["singpass", "myinfo"],
    ipAddress: "10.10.10.1",
  },
  {
    id: "a006",
    personaId: "p002",
    personaNric: "T0234567B",
    action: "approve",
    actor: "px.ops@singpass.gov.sg",
    actorRole: "PX Ops",
    timestamp: "2025-02-01T10:30:00Z",
    details: "Persona provisioning approved for CPF integration testing. Corppass admin role assigned.",
    systems: ["singpass", "myinfo", "corppass"],
    ipAddress: "10.20.30.5",
  },
  {
    id: "a007",
    personaId: "p006",
    personaNric: "T1898765E",
    action: "access",
    actor: "dev.team@mom.gov.sg",
    actorRole: "RP Developer",
    timestamp: "2025-03-13T14:11:00Z",
    details: "Renewal request submitted. Expiry: 2025-03-20. Awaiting PX Ops approval.",
    systems: [],
    ipAddress: "203.45.67.89",
  },
  {
    id: "a008",
    personaId: "p001",
    personaNric: "S9812345A",
    action: "modify",
    actor: "alice.lim@govtech.gov.sg",
    actorRole: "RP Developer",
    timestamp: "2025-03-02T14:20:00Z",
    details: "Myinfo attribute updated: housingType changed to HDB 4-Room for regression test coverage.",
    systems: ["myinfo"],
    ipAddress: "203.45.12.33",
  },
];

export const mockMetrics: DashboardMetrics = {
  totalPersonas: 42,
  activePersonas: 35,
  expiringPersonas: 4,
  provisioningToday: 3,
  avgProvisionTime: "4.2 hrs",
  teamsInvolved: 2,
  manualSteps: 4,
  errorRate: "1.8%",
  selfServiceRate: "72%",
  supportTickets: 2,
};
